package godocx

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	settingsRelType   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings"
	settingsPartName  = "/word/settings.xml"
	settingsContentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"

	minimalSettingsXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:updateFields w:val="1"/>
</w:settings>`
)

// fldCharBeginRe matches <w:fldChar w:fldCharType="begin" ...> elements that do
// not already carry w:dirty="true", so that markHeaderFooterFieldsDirty is
// idempotent and never double-inserts the attribute.
var fldCharBeginRe = regexp.MustCompile(`<w:fldChar\s[^>]*w:fldCharType="begin"[^>]*?>`)

// ForceFieldUpdateOnOpen instructs Word and LibreOffice to recalculate all
// field codes (PAGE, NUMPAGES, DATE, TOC, cross-references, etc.) the first
// time the document is opened. This is the correct approach for programmatically
// generated DOCX files where the rendered field values are not yet available.
//
// Behaviour:
//   - If word/settings.xml already exists (e.g. from an uploaded template),
//     <w:updateFields w:val="1"/> is inserted into the existing document.
//   - If word/settings.xml does not exist, a minimal one is created and wired
//     into both [Content_Types].xml and word/_rels/document.xml.rels.
//   - All header and footer XML parts in word/ are scanned and any
//     <w:fldChar w:fldCharType="begin"> elements are marked w:dirty="true"
//     so that their cached results are discarded on open, regardless of whether
//     the headers/footers came from a template or were generated by this library.
//   - Calling this method more than once is idempotent.
func (u *Updater) ForceFieldUpdateOnOpen() error {
	if u == nil {
		return fmt.Errorf("updater is nil")
	}

	settingsPath := filepath.Join(u.tempDir, "word", "settings.xml")

	if _, err := os.Stat(settingsPath); err == nil {
		if err := injectUpdateFields(settingsPath); err != nil {
			return err
		}
	} else {
		// settings.xml does not exist — create it and wire it up.
		if err := atomicWriteFile(settingsPath, []byte(minimalSettingsXML), 0o644); err != nil {
			return fmt.Errorf("write settings.xml: %w", err)
		}
		if err := u.addSettingsContentType(); err != nil {
			return fmt.Errorf("add settings content type: %w", err)
		}
		if err := u.addSettingsRelationship(); err != nil {
			return fmt.Errorf("add settings relationship: %w", err)
		}
	}

	// Mark field codes in all header and footer parts as dirty so that cached
	// results are discarded when the document is opened, even for template-
	// provided headers/footers that were never processed by this library.
	return u.markHeaderFooterFieldsDirty()
}

// markHeaderFooterFieldsDirty scans every word/header*.xml and word/footer*.xml
// file and adds w:dirty="true" to each <w:fldChar w:fldCharType="begin"> element
// that does not already carry the attribute. This is required because the
// document-level w:updateFields flag is not always honoured for header/footer
// parts by all Word and LibreOffice versions.
func (u *Updater) markHeaderFooterFieldsDirty() error {
	wordDir := filepath.Join(u.tempDir, "word")
	entries, err := os.ReadDir(wordDir)
	if err != nil {
		return fmt.Errorf("read word dir: %w", err)
	}

	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() {
			continue
		}
		isHeader := strings.HasPrefix(name, "header") && strings.HasSuffix(name, ".xml")
		isFooter := strings.HasPrefix(name, "footer") && strings.HasSuffix(name, ".xml")
		if !isHeader && !isFooter {
			continue
		}

		fullPath := filepath.Join(wordDir, name)
		if err := injectDirtyIntoFieldCodes(fullPath); err != nil {
			return fmt.Errorf("mark fields dirty in %s: %w", name, err)
		}
	}
	return nil
}

// injectDirtyIntoFieldCodes rewrites a single XML file so that every
// <w:fldChar w:fldCharType="begin"> element carries w:dirty="true".
// Elements that already have the attribute are left unchanged.
func injectDirtyIntoFieldCodes(xmlPath string) error {
	raw, err := os.ReadFile(xmlPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", xmlPath, err)
	}
	content := string(raw)

	updated := fldCharBeginRe.ReplaceAllStringFunc(content, func(match string) string {
		if strings.Contains(match, `w:dirty="true"`) {
			return match // already marked
		}
		// Insert the attribute before the closing > or />.
		if strings.HasSuffix(match, "/>") {
			return match[:len(match)-2] + ` w:dirty="true"/>`
		}
		return match[:len(match)-1] + ` w:dirty="true">`
	})

	if updated == content {
		return nil // nothing changed — skip the write
	}
	return atomicWriteFile(xmlPath, []byte(updated), 0o644)
}

// injectUpdateFields adds <w:updateFields w:val="1"/> to an existing settings.xml.
// It is idempotent: if the element is already present nothing is written.
func injectUpdateFields(settingsPath string) error {
	raw, err := os.ReadFile(settingsPath)
	if err != nil {
		return fmt.Errorf("read settings.xml: %w", err)
	}
	content := string(raw)

	if strings.Contains(content, "w:updateFields") {
		return nil // already present
	}

	// Insert immediately before </w:settings>.
	const closeTag = "</w:settings>"
	if !strings.Contains(content, closeTag) {
		// Malformed settings.xml — append the flag and closing tag.
		content += "\n<w:updateFields w:val=\"1\"/>\n" + closeTag
	} else {
		content = strings.Replace(content, closeTag,
			"<w:updateFields w:val=\"1\"/>\n"+closeTag, 1)
	}

	return atomicWriteFile(settingsPath, []byte(content), 0o644)
}

// addSettingsContentType registers word/settings.xml in [Content_Types].xml.
func (u *Updater) addSettingsContentType() error {
	ctPath := filepath.Join(u.tempDir, "[Content_Types].xml")
	raw, err := os.ReadFile(ctPath)
	if err != nil {
		return fmt.Errorf("read content types: %w", err)
	}
	content := string(raw)

	if strings.Contains(content, settingsPartName) {
		return nil // already registered
	}

	override := fmt.Sprintf(`<Override PartName="%s" ContentType="%s"/>`, settingsPartName, settingsContentType)
	content = strings.Replace(content, "</Types>", override+"</Types>", 1)
	return atomicWriteFile(ctPath, []byte(content), 0o644)
}

// addSettingsRelationship adds the settings relationship to word/_rels/document.xml.rels.
func (u *Updater) addSettingsRelationship() error {
	relsPath := filepath.Join(u.tempDir, "word", "_rels", "document.xml.rels")
	raw, err := os.ReadFile(relsPath)
	if err != nil {
		return fmt.Errorf("read document relationships: %w", err)
	}
	content := string(raw)

	if strings.Contains(content, settingsRelType) {
		return nil // already registered
	}

	relID, err := getNextRelIDFromFile(relsPath)
	if err != nil {
		return fmt.Errorf("find next relationship id: %w", err)
	}

	newRel := fmt.Sprintf(
		`<Relationship Id="%s" Type="%s" Target="settings.xml"/>`,
		relID, settingsRelType,
	)
	content = strings.Replace(content, "</Relationships>", newRel+"</Relationships>", 1)
	return atomicWriteFile(relsPath, []byte(content), 0o644)
}
